#!/usr/bin/bash
# ------------------------------------------------------------------------------
# This is a proxy for mini-bash-lib. If enabled it loads centauri-bash-lib
# instead of mini-bash-lib. There are 2 ways to disable this:
#
#   1)  CEN_FEATURE_N=1                 # before calling the proxy  -or-
#   2)  _mini_bash_lib  ... -n ...      # disable centauri-bash-lib
#
#   The proxy passes all arguments to centauri-bash-lib but always sets -a
#   -d -f (autoload dryrun force). It also registers quit_hook().
# ------------------------------------------------------------------------------

CEN_CMDDATA=
CEN_CMDCURR=1
CEN_NAME="${BASH_ARGV0##*/}"
while [ $# -ge "$CEN_CMDCURR" ] ; do    # parse arguments ...
    CEN_CMDDATA="${!CEN_CMDCURR}" ; ((CEN_CMDCURR += 1))
    case "$CEN_CMDDATA" in
    -m) ((CEN_CMDCURR += 1)) ;;         # skip value (module name)
    -f) CEN_FEATURE_F=1 ;;              # option --force
    -n) CEN_FEATURE_N=1 ;;              # disable centauri-bash-lib
    -t) CEN_FEATURE_T=1 ;;              # allow i10n
    -y) CEN_FEATURE_Y=1 ;;              # options --no and --yes
    -?) ;;                              # ignore
    -)  break ;;                        # end of options, no name
    *)  CEN_NAME="$CEN_CMDDATA" ; break # end of options
    esac
done
CEN_VERSION="${!CEN_CMDCURR}"
CEN_RUN_MIN_ARGS='-'                    # no arg count check

if [ -z "$CEN_FEATURE_N" ] ; then       # search for --mini option
    readarray -d '' -t CEN_CMDCURR <'/proc/self/cmdline'
    for CEN_CMDDATA in "${CEN_CMDCURR[@]}" ; do
       case "$CEN_CMDDATA" in
       ---) break ;;
       --mini*=0) CEN_FEATURE_N=0 ; break ;;
       --mini*=1) CEN_FEATURE_N=1 ; break
       esac
    done
fi
unset CEN_CMDCURR

if [ "$CEN_FEATURE_N" != 1 ] ; then     # try centauri-bash-lib
    CEN_CMDDATA=$(type -p '_centauri_bash_lib')
    CEN_CMDDATA="${CEN_CMDDATA%/*}/_centauri_bash_lib"
    [ -f "$CEN_CMDDATA" ] || CEN_FEATURE_N=1
fi
if [ "$CEN_FEATURE_N" = 1 ] ; then      # try mini-bash-lib
    CEN_CMDDATA=$(realpath "$BASH_SOURCE")
    CEN_CMDDATA="${CEN_CMDDATA%/*}/mini-bash-lib"
    [ -f "$CEN_CMDDATA" ] || return 127
fi
                                        # load packed version?
[ "${CEN_CMDDATA}.p" -nt "$CEN_CMDDATA" ] && CEN_CMDDATA+='.p'
source "$CEN_CMDDATA" -a -d -f "$@"

# end
